spring:
  application:
    name: consul-service
  redis:
    database: ${redis.database}
    host: ${redis.host}
    password: ${redis.password}
    port: ${redis.port}
    pool:
      max-active: ${redis.pool.max-active}
      min-idle: ${redis.pool.min-idle}
      max-wait:  ${redis.pool.max-wait}
      max-idle: ${redis.pool.max-idle}

  rabbitmq:
    addresses: 47.98.123.156
    username: guest
    password: guest

#druid:
#  type: com.alibaba.druid.pool.DruidDataSource
#  dbname:
#    master:
#      url: ${postgres.master}
#      driver-class-name: org.postgresql.Driver
#      username: ${postgres.username}
#      password: ${postgres.password}
#      initial-size: ${postgres.initSize}
#      min-idle: ${postgres.minIdle}
#      max-active: ${postgres.maxActive}
#      test-on-borrow: ${postgres.testOnBorrow}
#    slave:
#      url: ${postgres.slave}
#      driver-class-name: org.postgresql.Driver
#      username: ${postgres.username}
#      password: ${postgres.password}
#      initial-size: ${postgres.initSize}
#      min-idle: ${postgres.minIdle}
#      max-active: ${postgres.maxActive}
#      test-on-borrow: ${postgres.testOnBorrow}

  profiles:
    active: dev

#  redis:
#    database: ${redis.database}
#    host: ${redis.host}
#    password: ${redis.password}
#    port: ${redis.port}
#    jedis:
#      pool:
#        max-active: ${redis.pool.max-active}
#        min-idle: ${redis.pool.min-idle}
#        max-wait:  ${redis.pool.max-wait}
#        max-idle: ${redis.pool.max-idle}

server:
  port: 9988





