spring:
  application:
    name: consul-service
  redis:
    database: ${redis.database}
    host: ${redis.host}
    password: ${redis.password}
    port: ${redis.port}
    pool:
      max-active: ${redis.pool.max-active}
      min-idle: ${redis.pool.min-idle}
      max-wait:  ${redis.pool.max-wait}
      max-idle: ${redis.pool.max-idle}

  datasource:
    druid:
#      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.98.123.156:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: Zbw123456|
#      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50


  profiles:
    active: dev
  cloud:
    consul:
      config:
        watch:
          enabled: true

server:
  port: 9988

mybatis:
  type-aliases-package: com.zbw.model
  mapper-locations:
    - classpath:mybatis/*.xml
#  config-location: classpath:mybatis-config.xml

mapper:
  mappers:
      - com.zbw.utils.MWMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# http://127.0.0.1:9988/druid/index.html




