spring:
  application:
    name: consul-service

  profiles:
    active: dev

#  redis:
#    database: ${redis.database}
#    host: ${redis.host}
#    password: ${redis.password}
#    port: ${redis.port}
#    jedis:
#      pool:
#        max-active: ${redis.pool.max-active}
#        min-idle: ${redis.pool.min-idle}
#        max-wait:  ${redis.pool.max-wait}
#        max-idle: ${redis.pool.max-idle}

server:
  port: 9988





